extern uint8_t mon_door;
extern uint8_t mon_current_floor;
extern uint8_t mon_dir;
extern bool mon_req0;
extern bool mon_req1;
extern bool mon_req2;
extern bool mon_req3;
extern bool mon_req4;
extern bool mon_served;
void viol_move_with_open_door(void);
void viol_floor_bounds(void);
void viol_door_open_only_when_serving(void);
void viol_dir_consistent_up(void);
void viol_dir_consistent_down(void);
void viol_no_skip_up(void);
void viol_no_skip_down(void);
void viol_idle_correctness(void);
void viol_req_not_served_0(void);
void viol_req_not_served_1(void);
void viol_req_not_served_2(void);
void viol_req_not_served_3(void);
void viol_req_not_served_4(void);
void viol_starvation_0(void);
void viol_starvation_1(void);
void viol_starvation_2(void);
void viol_starvation_3(void);
void viol_starvation_4(void);
void step(void);
