#include <assert.h>

#include <stdbool.h>
#include <stdint.h>

#include "elevator.h"
#include "monitor_inputs.h"

/* Violation latch set by any monitor trigger callback. */
int violation = 0;
int violation_id = 0;
int violation_tick = -1;
int violation_floor = -1;
int monitor_tick = -1;

/*
 * Fault injection for monitor testing (disabled by default).
 * Build with e.g. `-DINJECT_CASE=8` to force violation 8.
 * Some cases use `INJECT_FLOOR` (0..4).
 */
#ifndef INJECT_CASE
#define INJECT_CASE 0
#endif

#ifndef INJECT_FLOOR
#define INJECT_FLOOR 0
#endif

#ifdef WITH_COPILOT
#include "elevator_mon.h" /* generated by Copilot from ElevatorMon.hs */

static void report_violation(int id, int floor) {
    if (!violation) {
        violation = 1;
        violation_id = id;
        violation_tick = monitor_tick;
        violation_floor = floor;
    }
}

/* Trigger callbacks (names must match ElevatorMon.hs). */
/*
 *  1  P1  "moved while door was open":
 *      Door was OPEN last tick, but floor changed this tick.
 *
 *  2  P2  "floor out of range":
 *      Reported floor is outside 0..FLOORS-1.
 *
 *  3  P3  "skipped a floor going UP":
 *      Last tick direction was UP, but floor jumped by more than +1.
 *
 *  4  P3  "skipped a floor going DOWN":
 *      Last tick direction was DOWN, but floor jumped by more than -1.
 *
 *  5  P4  "door opened for no valid service":
 *      Door is OPEN but `mon_served` is false.
 *
 *  6  P6  "claimed UP but actually went down":
 *      Last tick direction was UP, but floor decreased.
 *
 *  7  P6  "claimed DOWN but actually went up":
 *      Last tick direction was DOWN, but floor increased.
 *
 *  8  P7  "should be idle, but isn't":
 *      Door is CLOSED and there are no pending requests, but `dir != IDLE`.
 *
 *  100..104  P5  "request wasn't served within k=5 ticks":
 *      For floor i, request i stayed pending too long without serving at floor i.
 *      (100+i corresponds to req[i].)
 *
 *  200..204  P8  "request wasn't cleared within k=15 ticks" (bounded no-starvation):
 *      For floor i, request i stayed true too long without being cleared.
 *      (200+i corresponds to req[i].)
 */
void viol_move_with_open_door(void) { report_violation(1, -1); }
void viol_floor_bounds(void) { report_violation(2, -1); }
void viol_no_skip_up(void) { report_violation(3, -1); }
void viol_no_skip_down(void) { report_violation(4, -1); }
void viol_door_open_only_when_serving(void) { report_violation(5, -1); }
void viol_dir_consistent_up(void) { report_violation(6, -1); }
void viol_dir_consistent_down(void) { report_violation(7, -1); }
void viol_idle_correctness(void) { report_violation(8, -1); }

void viol_req_not_served_0(void) { report_violation(100, 0); }
void viol_req_not_served_1(void) { report_violation(101, 1); }
void viol_req_not_served_2(void) { report_violation(102, 2); }
void viol_req_not_served_3(void) { report_violation(103, 3); }
void viol_req_not_served_4(void) { report_violation(104, 4); }

void viol_starvation_0(void) { report_violation(200, 0); }
void viol_starvation_1(void) { report_violation(201, 1); }
void viol_starvation_2(void) { report_violation(202, 2); }
void viol_starvation_3(void) { report_violation(203, 3); }
void viol_starvation_4(void) { report_violation(204, 4); }

static void inject_monitor_inputs(void) {
#if INJECT_CASE != 0
    /*
     * Important: this mutates ONLY the `mon_*` snapshot (what the monitor sees),
     * not the controller state. Call after `monitor_inputs_update()` and before
     * Copilot `step()`.
     */

#if INJECT_CASE == 1
    /* P1: moved while door was open (prev door OPEN, then floor changes) */
    if (monitor_tick == 0) {
        mon_current_floor = 0;
        mon_dir = 0;  /* IDLE */
        mon_door = 0; /* OPEN */
        mon_served = true;
        mon_req0 = false;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
    }
    if (monitor_tick == 1) {
        mon_current_floor = 1;
        mon_dir = 0;   /* IDLE */
        mon_door = 1;  /* CLOSED */
        mon_served = true;
        mon_req0 = false;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
    }

#elif INJECT_CASE == 2
    /* P2: floor out of bounds */
    if (monitor_tick == 0) {
        mon_dir = 0;  /* IDLE */
        mon_door = 1; /* CLOSED */
        mon_served = true;
        mon_req0 = false;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
        mon_current_floor = 5;
    }

#elif INJECT_CASE == 3
    /* P3 (UP): skip floors (+2 jump) */
    if (monitor_tick == 0) {
        mon_current_floor = 0;
        mon_dir = 1;  /* UP */
        mon_door = 1; /* CLOSED */
        mon_served = false;
        /* Avoid unrelated P7 failures: make sure there is at least one pending request. */
        mon_req0 = true;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
    }
    if (monitor_tick == 1) {
        mon_current_floor = 2;
        mon_dir = 1;  /* UP */
        mon_door = 1; /* CLOSED */
        mon_served = false;
        mon_req0 = true;
    }

#elif INJECT_CASE == 4
    /* P3 (DOWN): skip floors (-2 jump) */
    if (monitor_tick == 0) {
        mon_current_floor = 4;
        mon_dir = 2;  /* DOWN */
        mon_door = 1; /* CLOSED */
        mon_served = false;
        mon_req0 = true;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
    }
    if (monitor_tick == 1) {
        mon_current_floor = 2;
        mon_dir = 2;  /* DOWN */
        mon_door = 1; /* CLOSED */
        mon_served = false;
        mon_req0 = true;
    }

#elif INJECT_CASE == 5
    /* P4: door open only when serving (door OPEN but mon_served FALSE) */
    if (monitor_tick == 0) {
        mon_current_floor = 0;
        mon_dir = 0;     /* IDLE */
        mon_door = 0;    /* OPEN */
        mon_served = false;
        mon_req0 = false;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
    }
    if (monitor_tick == 1) {
        /* Keep floor stable so this case doesn't also create a P1 counterexample. */
        mon_current_floor = 0;
        mon_dir = 0;     /* IDLE */
        mon_door = 0;    /* OPEN */
        mon_served = false;
    }

#elif INJECT_CASE == 6
    /* P6 (UP): claimed UP but floor decreased */
    if (monitor_tick == 0) {
        mon_current_floor = 2;
        mon_dir = 1;  /* UP */
        mon_door = 1; /* CLOSED */
        mon_served = false;
        /* Avoid unrelated P7 failures while dir != IDLE. */
        mon_req0 = true;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
    }
    if (monitor_tick == 1) {
        mon_current_floor = 1;
        mon_dir = 1;  /* UP */
        mon_door = 1; /* CLOSED */
        mon_served = false;
        mon_req0 = true;
    }

#elif INJECT_CASE == 7
    /* P6 (DOWN): claimed DOWN but floor increased */
    if (monitor_tick == 0) {
        /* Prevent unrelated violations (e.g., P1/P7) from being the first latch. */
        mon_door = 1; /* CLOSED */
        mon_req0 = true;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
        mon_served = false;
        mon_current_floor = 2;
        mon_dir = 2; /* DOWN */
    }
    if (monitor_tick == 1) {
        mon_door = 1; /* CLOSED */
        mon_req0 = true;
        mon_current_floor = 3;
        mon_dir = 2; /* DOWN */
    }

#elif INJECT_CASE == 8
    /* P7: idle correctness (no requests + door closed, but dir != IDLE) */
    if (monitor_tick == 0) {
        mon_current_floor = 0;
        mon_door = 1; /* CLOSED */
        mon_req0 = false;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
        mon_served = false;
        mon_dir = 1; /* UP */
    }

#elif INJECT_CASE == 9
    /* P5: req[INJECT_FLOOR] not served within kServe (default 5) */
    if (monitor_tick <= 10) {
        mon_current_floor = (uint8_t)INJECT_FLOOR;
        mon_dir = 0;  /* IDLE */
        mon_door = 1; /* keep CLOSED so servedAtFloor never happens */
        mon_served = false;
        mon_req0 = false;
        mon_req1 = false;
        mon_req2 = false;
        mon_req3 = false;
        mon_req4 = false;
        if (INJECT_FLOOR == 0) mon_req0 = true;
        if (INJECT_FLOOR == 1) mon_req1 = true;
        if (INJECT_FLOOR == 2) mon_req2 = true;
        if (INJECT_FLOOR == 3) mon_req3 = true;
        if (INJECT_FLOOR == 4) mon_req4 = true;
    }

#elif INJECT_CASE == 10
    /*
     * P8: req[INJECT_FLOOR] not cleared within kStarve (default 15)
     * NOTE: Requires a trace longer than kStarve to witness the expiry.
     *
     * We keep the door OPEN at the injected floor with mon_served=true so P5
     * is not triggered first via servedAtFloor (this case is about clearing).
     */
    mon_current_floor = (uint8_t)INJECT_FLOOR;
    mon_dir = 0;   /* IDLE */
    mon_door = 0;  /* OPEN */
    mon_served = true;
    mon_req0 = false;
    mon_req1 = false;
    mon_req2 = false;
    mon_req3 = false;
    mon_req4 = false;
    if (INJECT_FLOOR == 0) mon_req0 = true;
    if (INJECT_FLOOR == 1) mon_req1 = true;
    if (INJECT_FLOOR == 2) mon_req2 = true;
    if (INJECT_FLOOR == 3) mon_req3 = true;
    if (INJECT_FLOOR == 4) mon_req4 = true;

#endif
#endif
}
#endif

int main(void) {
    elevator_init();
    monitor_inputs_update();

#ifndef MAIN_TICKS
#define MAIN_TICKS 15
#endif

    for (int i = 0; i < MAIN_TICKS; i++) {
        monitor_tick = i;
        system_step();
        monitor_inputs_update();

#ifdef WITH_COPILOT
        inject_monitor_inputs();
        step();
#endif
    }

#ifdef VERIFY
#ifdef CBMC
    /*
     * For CBMC: make the failing property name explicit.
     * Read `violation_id`, `violation_tick`, and `violation_floor` in the trace.
     */
    __CPROVER_assert(violation_id != 1, "P1: no movement when door open");
    __CPROVER_assert(violation_id != 2, "P2: floor bounds");
    __CPROVER_assert(violation_id != 3, "P3: no skipping floors (UP)");
    __CPROVER_assert(violation_id != 4, "P3: no skipping floors (DOWN)");
    __CPROVER_assert(violation_id != 5, "P4: door opens only when serving");
    __CPROVER_assert(violation_id != 6, "P6: direction consistency (UP)");
    __CPROVER_assert(violation_id != 7, "P6: direction consistency (DOWN)");
    __CPROVER_assert(violation_id != 8, "P7: idle correctness");

    /* P5 (bounded service, k=5) */
    __CPROVER_assert(violation_id != 100, "P5: req[0] served within k");
    __CPROVER_assert(violation_id != 101, "P5: req[1] served within k");
    __CPROVER_assert(violation_id != 102, "P5: req[2] served within k");
    __CPROVER_assert(violation_id != 103, "P5: req[3] served within k");
    __CPROVER_assert(violation_id != 104, "P5: req[4] served within k");

    /* P8 (bounded no-starvation, k=15) */
    __CPROVER_assert(violation_id != 200, "P8: req[0] eventually cleared within k");
    __CPROVER_assert(violation_id != 201, "P8: req[1] eventually cleared within k");
    __CPROVER_assert(violation_id != 202, "P8: req[2] eventually cleared within k");
    __CPROVER_assert(violation_id != 203, "P8: req[3] eventually cleared within k");
    __CPROVER_assert(violation_id != 204, "P8: req[4] eventually cleared within k");
#else
    assert(!violation);
#endif
#endif
    return violation ? 1 : 0;
}
