#include <stdio.h>
#include <stdbool.h>
#include <unistd.h>
#include "engine.h"

/* external variables used by Copilot */
float temp;
bool running;

/* trigger function generated by Copilot */
void over_temp_rise(void)
{
    printf("ALERT: Temperature rose too quickly while injector running!\n");
}
/*If the temperature rises more than 2.3°C within 0.2 seconds, the fuel injector must not be running.*/
int main()
{
    /* simulated temperature readings */
    float temps[] = {80.0, 81.0, 83.6, 84.0, 84.5, 87.0, 87.2, 90.0};
    bool injector_state[] = {true, true, true, true, false, true, true, true};

    int n = sizeof(temps) / sizeof(temps[0]);

    for (int i = 0; i < n; i++)
    {
        temp = temps[i];
        running = injector_state[i];

        printf("Temp: %.2f  | Injector running: %d\n", temp, running);

        /* run one step of the Copilot monitor */
        step();

        sleep(1);
    }

    return 0;
}
