extern bool fault;
extern bool safe_mode;
extern bool gas_pressed;
extern bool brake;
extern bool engine;
extern float brake_torque;
extern bool abrupt_gas;
extern float torque;
extern bool acc;
extern float wsl;
extern float wsr;
extern bool stationary;
extern bool collision_imminent;
extern bool rolling;
extern bool brake_request;
extern float gas_angle;
void viol_torque_limit(void);
void viol_brake_acc_conflict(void);
void viol_wheel_speed_mismatch(void);
void viol_fault_safe_mode(void);
void viol_r1_collision_response(void);
void viol_r2_gas_override(void);
void viol_ac_engine_mapping(void);
void viol_gc_brake_torque_zero(void);
void viol_gf_torque_min(void);
void step(void);
