#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 199309L
#endif

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <time.h>

#include "automotive_system.h" /* generated by Copilot */
#include "nondet.h"

#ifndef TICK_MS
#define TICK_MS 100
#endif

#ifndef MAX_TICKS
#define MAX_TICKS 200
#endif

#ifndef INJECT_CASE
#define INJECT_CASE 0
#endif

/* Externs used by the Copilot monitor (must match automotive_system.hs). */
float torque;
bool brake;
bool acc;

float wsl;
float wsr;

bool fault;
bool safe_mode;

bool stationary;
bool rolling;
bool collision_imminent;

bool engine;
bool gas_pressed;
float gas_angle;
bool brake_request;

float brake_torque;
bool abrupt_gas;

/* Trigger callbacks (must match automotive_system.hs). */
void viol_torque_limit(void) { printf("[VIOL] torque > 350\n"); }
void viol_brake_acc_conflict(void) { printf("[VIOL] brake && acc\n"); }
void viol_wheel_speed_mismatch(void) { printf("[VIOL] |WSL-WSR| too large\n"); }
void viol_fault_safe_mode(void) { printf("[VIOL] fault not followed by safe_mode in time\n"); }

void viol_r1_collision_response(void) { printf("[VIOL] R1 collision response\n"); }
void viol_r2_gas_override(void) { printf("[VIOL] R2 gas override bounded\n"); }
void viol_ac_engine_mapping(void) { printf("[VIOL] A.C engine mapping violated\n"); }
void viol_gc_brake_torque_zero(void) { printf("[VIOL] G.C brake_torque not reduced in time\n"); }
void viol_gf_torque_min(void) { printf("[VIOL] G.F torque not reduced to min in time\n"); }

static void tick_sleep(void) {
#ifndef FAST
    struct timespec ts;
    ts.tv_sec = (time_t)(TICK_MS / 1000);
    ts.tv_nsec = (long)(TICK_MS % 1000) * 1000000L;
    nanosleep(&ts, NULL);
#endif
}

static bool maybe(bool p_true) {
    /* crude Bernoulli via u32 */
    uint32_t r = nondet_u32();
    /* p_true in [0,1] mapped to threshold */
    uint32_t thresh = (uint32_t)(p_true * 4294967295.0f);
    return r <= thresh;
}

int main(void) {
    /* simple internal state for bounded responses */
    int safe_mode_timer = -1;
    int gas_timer = -1;
    int brake_torque_timer = -1;
    int torque_min_timer = -1;

    /* initial values */
    torque = 0.0f;
    brake = false;
    acc = false;
    wsl = 10.0f;
    wsr = 10.0f;
    fault = false;
    safe_mode = false;
    stationary = true;
    rolling = false;
    collision_imminent = false;
    engine = false;
    gas_pressed = false;
    gas_angle = 0.0f;
    brake_request = false;
    brake_torque = 0.0f;
    abrupt_gas = false;

    for (int t = 0; t < MAX_TICKS; t++) {
        /* Inputs */
        stationary = maybe(0.2f);
        rolling = !stationary && maybe(0.5f);
        collision_imminent = maybe(0.05f);

        gas_angle = nondet_float_range(0.0f, 1.0f);
        gas_pressed = gas_angle > 0.6f;
        abrupt_gas = maybe(0.03f);

        brake_request = maybe(0.2f);

        /* Actuators / outputs (pseudo controller designed to satisfy specs by default). */

        /* Mutual exclusion policy: never allow brake and acc both true. */
        acc = gas_pressed;
        brake = (!gas_pressed) && brake_request;

        /* Engine mapping f(gas_angle): engine engaged iff gas_angle > 0.2 when allowed. */
        bool engine_should_follow_map = (stationary || rolling) && !brake_request;
        bool engine_map = (gas_angle > 0.2f);
        if (engine_should_follow_map) {
            engine = engine_map;
        } else {
            /* otherwise, leave engine as-is but allow gas_pressed to start it soon */
            if (gas_pressed) engine = true;
        }

        /* R1: if stationary and collision imminent -> brake=1 and engine=0 (strong safety). */
        if (stationary && collision_imminent) {
            brake = true;
            acc = false;
            engine = false;
        }

        /* Fault and safe mode: when fault occurs, enter safe mode within 3 ticks. */
        fault = maybe(0.03f);
        if (fault) {
            safe_mode_timer = 3;
        }
        if (safe_mode_timer >= 0) {
            if (safe_mode_timer == 0) {
                safe_mode = true;
            } else {
                safe_mode_timer--;
            }
        } else {
            safe_mode = false;
        }

        /* R2: gas_pressed -> within T steps brake=0 and engine=1.
         * Choose T=3. */
        if (gas_pressed) {
            gas_timer = 3;
        }
        if (gas_timer >= 0) {
            brake = false;
            engine = true;
            if (gas_timer > 0) gas_timer--;
        }

        /* G.C: gas_pressed -> within 5 steps brake_torque=0.
         * We model brake_torque as non-negative. */
        if (gas_pressed) {
            brake_torque_timer = 5;
            brake_torque = nondet_float_range(0.0f, 300.0f);
        }
        if (brake_torque_timer >= 0) {
            if (brake_torque_timer == 0) {
                brake_torque = 0.0f;
            } else {
                brake_torque_timer--;
            }
        } else {
            brake_torque = nondet_float_range(0.0f, 50.0f);
        }

        /* G.F: abrupt_gas -> within 5 steps engine torque reduces to min (0). */
        if (abrupt_gas) {
            torque_min_timer = 5;
        }

        /* Torque generation (respect limit by default). */
        if (torque_min_timer >= 0) {
            if (torque_min_timer == 0) {
                torque = 0.0f;
            } else {
                /* ramp down */
                torque *= 0.5f;
                torque_min_timer--;
            }
        } else {
            torque = nondet_float_range(0.0f, 340.0f);
        }

        /* Wheel speeds: keep mismatch within 15% by construction. */
        wsl = nondet_float_range(5.0f, 50.0f);
        float max_delta = 0.15f * wsl;
        float delta = nondet_float_range(-max_delta, max_delta);
        wsr = wsl + delta;

#if INJECT_CASE == 1
        /* Force torque violation */
        if (t == 10) torque = 400.0f;
#elif INJECT_CASE == 2
        /* Force brake/acc conflict */
        if (t == 10) { brake = true; acc = true; }
#elif INJECT_CASE == 3
        /* Force wheel speed mismatch */
        if (t == 10) { wsl = 20.0f; wsr = 30.0f; }
#elif INJECT_CASE == 4
        /* Force fault response violation */
        if (t == 10) { fault = true; safe_mode = false; safe_mode_timer = -1; }
#endif

        printf("t=%d torque=%.1f brake=%d acc=%d wsl=%.1f wsr=%.1f fault=%d safe=%d engine=%d\n",
               t, torque, brake, acc, wsl, wsr, fault, safe_mode, engine);

        step();
        tick_sleep();
    }

    return 0;
}
